<?php

namespace frontend\controllers;





use backend\models\Group;

use backend\models\MainApp;

use backend\models\Tblcategory;

use backend\models\TblcategoryProduct;

use backend\models\TblCoordinates;

use backend\models\TblPresence;

use backend\models\Tblproduct;

use backend\models\TblProfile;

use common\components\jdf;

use common\models\User;

use frontend\models\Categoryproduct;

use frontend\models\Exist;

use frontend\models\FaceExist;

use frontend\models\Factor;

use frontend\models\Gallery;

use frontend\models\PHPWebSocket;

use frontend\models\Product;

use frontend\models\Profile;

use frontend\models\Tblbag;

use frontend\models\Tblbrand;

use frontend\models\UserMain;

use phpDocumentor\Reflection\Types\Null_;

use yii;

use yii\rest\ActiveController;





/**

 * Country Controller API

 *

 * @author Budi Irawan <deerawan@gmail.com>

 */

class AndroidController extends ActiveController

{

    public $modelClass = 'frontend\models\Tblsize';





    public function init()

    {

        if (\Yii::$app->request->authUser != null && \Yii::$app->request->authPassword != null) {



            $username = \Yii::$app->request->authUser;;

            $password = \Yii::$app->request->authPassword;

            $user = User::findByUsername($username);

            if ($user != null) {

                if ($user->validatePassword($password)) {

                    Yii::$app->getUser()->login($user);



                } else {

                    print "ÛŒÙˆØ²Ø± Ùˆ Ù¾Ø³ÙˆØ±Ø¯ Ø´Ù…Ø§ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

                    exit;

                }

            }

        }



        parent::init();

        \Yii::$app->user->enableSession = false;

    }





    public function behaviors()

    {

        $behaviors = parent::behaviors();

        $behaviors['authenticator'] = [

            'class' => yii\filters\auth\HttpBasicAuth::className(),

            'auth' => function ($user, $pass) {

                $user = User::findByUsername($user);

                if ($user != null) {

                    return $user;

                }



            },

            'only' => ['myorderse'],

        ];

        $behaviors['access'] = [



            'class' => yii\filters\AccessControl::className(),

            'only' => ['signup', 'savepres', 'login', 'getpolyline', 'cart', 'detail_cart', 'cart_update', 'payment', 'listfactor', 'listcart'],

            'rules' => [

                [

                    'actions' => ['signup', 'login', 'display_main', 'cart', 'detail_cart', 'cart_update', 'payment', 'listfactor', 'listcart'],

                    'allow' => true,

                    'roles' => ['?'],

                ],



                [

                    'actions' => ['getpolyline', 'savepres', 'login', 'test2', 'display_main', 'cart', 'detail_cart', 'cart_update', 'payment', 'listfactor', 'listcart'],

                    'allow' => true,

                    'roles' => ['@'],

                ],

            ],

        ];



        return $behaviors;

    }



    public function checkAccess($action, $model = null, $params = [])

    {

        return $model;

    }



    public function actions()

    {

        $action = parent::actions(); // TODO: Change the autogenerated stub

        unset($action['create']);

        return $action;

    }



    public function actionDisplay_main()

    {

        $pro = Product::find()->orderBy(["id" => SORT_DESC])->all();

        $countPro = 0;

        $namePro = null;



        $model = new MainApp();

        $main = $model->find()->all();

        $group2 = Group::find()->where(['enabel' => 1])->andWhere(['enabel_view' => 1])->all();

        $group = null;

        if ($pro != null && $group2 != null && $main != null) {

            if ($pro != null) {

                foreach ($pro as $rowPro) {

                    if ($countPro == 0) {

                        $namePro =  $rowPro->name. "##".$rowPro->id  ;

                    } else {

                        $namePro .= "@@"  . $rowPro->name."##".$rowPro->id ;

                    }

                    $countPro++;

                }

            }

            foreach ($group2 as $g) {

                $group .= $g->id . '_' . $g->city . '-' . $g->location . ',';

            }

            foreach ($main as $row) {

                if ($row->type != null) {

                    $send['type'] = $row->type;

                    $send['m_d_f'] = $row->m_d_f;

                    $send['id_m_d_f'] = $row->id_m_d_f;

                    $send['urlimg'] = $row->urlimg;

                    $send['img1'] = $row->img1;

                    $send['img2'] = $row->img2;

                    $send['img3'] = $row->img3;

                    $send['img4'] = $row->img4;

                    $send['id1'] = $row->id1;

                    $send['id2'] = $row->id2;

                    $send['id3'] = $row->id3;

                    $send['id4'] = $row->id4;

                    ($row->headrtype!=null ? $headrtype = $row->headrtype : $headrtype = "Ù†Ù…Ø§ÛŒØ´" );

                    ($row->footertype!=null ? $footertype = $row->footertype : $footertype = "Ù†Ù…Ø§ÛŒØ´" );

                    $send['headerType'] = $headrtype;

                    $send['footerType'] = $footertype ;

                    $send['text1'] = $row->text1;

                    $send['text2'] = $row->text2;

                    $send['text3'] = $row->text3;

                    $sendFull[] = $send;

                }

                $sendOk["result"] = 1;

                $sendOk["pro"] = $sendFull;

                $sendOk["group"] = $group;

                $sendOk["name"] = $namePro;

            }

        } else {

            $sendOk["result"] = 0;

            $sendOk["msg"] = "ÛŒÚ©ÛŒ Ø§Ø² Ø³Ù‡ Ù…ÙˆØ±Ø¯ Ø²ÛŒØ± Ø®Ø§Ù„ÛŒ Ø§Ø³Øª 1- Ù†Ø§Ù… Ù…Ø­ØµÙˆÙ„ 2- Ù…Ù†Ø§Ø·Ù‚ 3- ØµÙØ­Ù‡ Ø§ÙˆÙ„ Ø§Ù¾Ù„ÛŒÚ©ÛŒØ´Ù†";

        }

        return $sendOk;

    }



    public function actionPayment()

    {

        if (isset($_POST['adress']) && $_POST['adress'] != null && isset($_POST['newAdress']) && $_POST['newAdress'] != null && isset($_POST['group']) && $_POST['group'] != null) {



            if (Yii::$app->user->isGuest) {



                print "  Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯ ";

                exit;

            }

            $tblGroup = new Group();

            $profile = Profile::find()->where(['id_user' => Yii::$app->user->id])->one();

            if ($_POST['newAdress'] == "new") {

                if ($_POST['adress'] != 'void') {

                    $adress = $_POST['adress'];

                } else {

                    $adress = $profile->addres;

                }

            } else {

                $adress = $profile->addres;

            }



            if ($_POST['group'] != 'void') {

                $gro = $_POST['group'];

                $gro1 = explode("_", $gro);

                $location = $gro1[0];

            } else {

                $gro = $tblGroup->find()->where(['id' => $profile->location])->one();

                if ($gro != null) {

                    $location = $gro->location;

                } else {

                    $location = 0;

                }

            }

            $tblBag = new Tblbag();

            $tblFactor = new Factor();



//  Ø¯Ø± Ø§Ø¨ØªØ¯Ø§ Ø¨Ø§ÛŒØ¯ Ú†Ú© Ø´ÙˆØ¯ Ù…Ø­ØµÙˆÙ„Ø§Øª Ù…ÙˆØ¬ÙˆØ¯ Ù‡Ø³ØªÙ† ÛŒØ§ Ø®ÛŒØ±

            $bag = $tblBag->find()->where(['id_user' => Yii::$app->user->id])->andWhere(['down_buy' => 0])->all();

            $count = $tblBag->find()->where(['id_user' => Yii::$app->user->id])->andWhere(['down_buy' => 0])->count();


            $date=new jdf();
            $time=$date->date('Y/m/d');
            $time_ir=explode('/',$time);
            $time_ir[0];
            $time_ir[1];

            $exist_all=Exist::find()->where(['enabel_view'=>1])->andWhere(['year'=>$time_ir[0]])->andWhere(['month'=>$time_ir[1]])->all();

            //        Ù‚Ø³Ù…Øª * Ø¯Ø§Ø±

//        Ø¯Ø± Ø§ÛŒÙ† Ù‚Ø³Ù…Øª Ø§Ú¯Ø± Ø®Ø±ÛŒØ¯ Ù†Ù‡Ø§ÛŒÛŒ Ù†Ø´Ø¯Ù‡ Ø¨Ø§Ø´Ø¯ Ø§Ø¨ØªØ¯Ø§ ØªÙ…Ø§Ù… ØªØºÛŒÛŒØ±Ø§ØªÛŒ Ú©Ù‡ Ø±ÙˆÛŒ Ù…ÙˆØ¬ÙˆØ¯ÛŒ Ø¬Ø¯ÙˆÙ„ face_exist Ù‘Ø¨Ù‡ ÙˆØ¬ÙˆØ¯ Ø§Ù…Ø¯Ù‡ Ø§Ø³Øª Ù¾Ø§Ú© Ù…ÛŒØ´ÙˆØ¯ ØªØ§ Ù…ÙˆØ­ÙˆØ¯ÛŒ Ù…Ø­ØµÙˆÙ„Ø§Øª Ø¯Ø±Ø³Øª Ø³Øª Ø´ÙˆØ¯

            $face2 = FaceExist::find()->where(['id_user' => Yii::$app->user->id])->all();

            if ($face2 != null) {

                foreach ($face2 as $f) {

                    $f->delete();

                }

            }



            //Ø¯Ø± Ø§ÛŒÙ† Ù‚Ø³Ù…Øª Ù…ÙˆØ¬ÙˆØ¯ÛŒ ØªÙ…Ø§Ù… Ù…Ø­ØµÙˆÙ„Ø§Øª Ø¯Ø± Ø¬Ø¯ÙˆÙ„ÛŒ Ø¨Ù‡ Ù†Ø§Ù… face_exist Ø°Ø®ÛŒØ±Ù‡ Ù…ÛŒØ´ÙˆØ¯  Ùˆ Ú†Ú© Ù…ÛŒØ´ÙˆØ¯ Ú©Ù‡ Ø§Ø² ÛŒÚ© Ù…Ø­ØµÙˆÙ„ Ùˆ Ø¯Ø± ÛŒÚ© ÙØ±ÙˆØ´Ú¯Ø§Ù‡ Ø®Ø§Øµ Ú†Ù†Ø¯ÛŒÙ† Ø¨Ø§Ø± Ø°Ø®ÛŒØ±Ù‡ Ù†Ø´ÙˆØ¯

            foreach ($exist_all as $c) {

                $exist = Exist::find()->where(['id_pro' => $c->id_pro])->andWhere(['store' =>10])->andWhere(['enabel_view' => 1])->one();

                $face = new FaceExist();

                $face->id_pro = $c->id_pro;

                $face->exist = $exist->exist_all;

                $face->store =10;

                $face->id_user = Yii::$app->user->id;

                $check = FaceExist::find()->where(['id_pro' => $c->id_pro])->andWhere(['store' =>10])->andWhere(['id_user' => Yii::$app->user->id])->count();

                if ($check == 0) {

                    $face->save();

                }

            }

            foreach ($bag as $b) {

//Ø§ÛŒÙ† Ø¬Ø¯ÙˆÙ„ Ø¯Ø± Ø¨Ø§Ù„Ø§ Ø³Øª Ø´Ø¯Ù‡ Ø§Ø³Øª Ùˆ Ù…ÙˆØ¬ÙˆØ¯ÛŒ Ù…Ø­ØµÙˆÙ„Ø§Øª Ø±Ø§ Ø¯Ø§Ø±Ø¯ Ø¨Ù‡ Ø§Ø²Ø§ÛŒ Ù‡Ø± Ù…Ø­ØµÙˆÙ„ Ø¯Ø± Ø¬Ø¯ÙˆÙ„ Ø¨Ú¯ Ù…ÙˆØ¬ÙˆØ¯ÛŒ Ú†Ú© Ù…ÛŒØ´ÙˆØ¯ Ø§Ú¯Ø±



                $exist = FaceExist::find()->where(['id_pro' => $b->id_pro])->andWhere(['store' => 10])->andWhere(['id_user' => Yii::$app->user->id])->one();

//ØªØ¹Ø¯Ø§Ø¯ Ù…Ø­ØµÙˆÙ„Ø§Øª Ø®Ø±ÛŒØ¯Ø§Ø±ÛŒ Ø´Ø¯Ù‡ Ø§Ø² Ù…ÙˆØ¬ÙˆØ¯ÛŒ Ø¨ÛŒØ´ØªØ± Ø¨Ø§Ø´Ø¯ Ù…Ø­ØµÙˆÙ„ Ø§Ø² Ø¬Ø¯ÙˆÙ„ Ø¨Ú¯ Ù¾Ø§Ú© Ù…ÛŒØ´ÙˆØ¯

                if ($exist->exist < $b->count) {



                    $b->delete();

                } else {

                    // Ø§Ú¯Ø± Ú©Ù…ØªØ± Ø¨Ø§Ø´Ø¯ ØªØ¹Ø¯Ø§Ø¯ Ø§Ø² Ø¬Ø¯ÙˆÙ„ face_exist Ú©Ù… Ù…ÛŒØ´ÙˆØ¯ Ùˆ Ø§ÛŒÙ† Ø¬Ø¯ÙˆÙ„ Ø§Ù¾Ø¯ÛŒØª Ù…ÛŒØ´ÙˆØ¯ Ø¨Ø±Ø§ÛŒ Ù…Ù‚Ø§ÛŒØ³Ù‡ Ù‡Ø§ÛŒ Ø¨Ø¹Ø¯ÛŒ

                    $exist->exist = $exist->exist - $b->count;

                    $exist->save();

                }

            }

            $count2 = $tblBag->find()->where(['id_user' => Yii::$app->user->id])->andWhere(['down_buy' => 0])->count();

            if ($count != $count2) {



                $send['result'] = 2; // Ù…Ø­ØµÙˆÙ„Ø§ØªÛŒ Ø§Ø² Ø³Ø¨Ø¯ Ø®Ø±ÛŒØ¯ Ø¨Ù‡ Ø¯Ù„ÛŒÙ„ Ú©Ù… Ø¨ÙˆØ¯Ù† Ù…ÙˆØ¬ÙˆØ¯ÛŒ Ù…Ø­ØµÙˆÙ„ Ø§Ø² Ø¬Ø¯ÙˆÙ„ bag Ù¾Ø§Ú© Ø´Ø¯Ù‡ Ø§Ø³Øª

                return $send;

            } else {

                $bag2 = $tblBag->find()->where(['id_user' => Yii::$app->user->id])->andWhere(['down_buy' => 0])->all();

                if ($bag2 != null) {

                    $tblFactor->data = date('Y/m/d');

                    $date = new jdf();

                    $tblFactor->data_ir = $date->date('Y/m/d');

                    $tblFactor->id_user = Yii::$app->user->id;

//   Ø­Ø³Ø§Ø¨ Ú©Ø±Ø¯Ù† Ù‚ÛŒÙ…Øª Ù†Ù‡Ø§ÛŒÛŒ  //

                    // 1-Ø­Ø³Ø§Ø¨ Ú©Ø±Ø¯Ù† Ø¬Ù…Ø¹ Ù‚ÛŒÙ…Øª Ù‡Ø§ÛŒ Ù…Ø­ØµÙˆÙ„Ø§Øª Ø¬Ø¯ÙˆÙ„ Ø¨Ú¯

                    $price_bag = 0;



                    foreach ($bag2 as $b2) {

                        $price_bag += $b2->price;

                    }

                    //2- Ø­Ø³Ø§Ø¨ Ú©Ø±Ø¯Ù† ØªØ®ÙÛŒÙ Ù…Ø¹Ø±Ù Ø¨ÙˆØ¯Ù†

                    $check_moaref = \frontend\models\Profile::find()->where(['id_user_moaref' => Yii::$app->user->getId()])->all();

                    $check_profile = Profile::find()->where(['id_user' => Yii::$app->user->getId()])->one();

                    if ($check_moaref != null) {

                        if ($check_profile->true_moaref == 0) {

                            // ÛŒØ¹Ù†ÛŒ Ú©Ø§Ø±Ø¨Ø±  Ø¨Ø±Ø§ÛŒ Ø¨Ø§Ø± Ø§ÙˆÙ„  Ø§Ø³Øª Ú©Ù‡ Ø§Ø² ØªØ®ÙÛŒÙ Ù…Ø¹Ø±Ù Ø¨ÙˆØ¯Ù† Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒÚ©Ù†Ø¯

                            $moaref = 10 / 100;



                        } else {

                            //  Ú©Ø§Ø±Ø¨Ø± ÛŒÚ© Ø¨Ø§Ø± Ø§Ø² Ú©Ø¯ ØªØ®ÙÛŒÙ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ø±Ø¯Ù‡ Ø§Ø³Øª Ùˆ True_moaref=1Ø´Ø¯Ù‡ Ùˆ Ø¯ÛŒÚ¯Ø± Ø¨Ù‡ Ø§Ùˆ ØªØ®ÙÛŒÙ ØªØ¹Ù„Ù‚ Ù†Ù…ÛŒÚ¯ÛŒØ±Ø¯

                            $moaref = 1;

                        }

                    } else {

                        // Ú©Ø§Ø±Ø¨Ø± Ù…Ø¹Ø±Ù Ú©Ø³ÛŒ Ù†Ø¨ÙˆØ¯Ù‡ Ø§Ø³Øª

                        $moaref = 1;

                    }

                    if ($moaref == 1) {

                        $newsum1 = $price_bag;

                    } else {

                        $newsum1 = $price_bag - ($price_bag * $moaref);

                    }

                    // 3- Ù…Ø­Ø§Ø³Ø¨Ù‡ Ø§Ø¹ØªØ¨Ø§Ø±

                    if ($check_profile->true_off >= 0) {

                        //Ø¯Ø± Ø§ÛŒÙ† Ø­Ø§Ù„Øª ØªÙ…Ø§Ù… Ø§Ø¹ØªØ¨Ø§Ø± Ø´Ø®Øµ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒ Ø´ÙˆØ¯

                        if ($newsum1 >= $check_profile->true_off) {

                            $newsum = $newsum1 - $check_profile->true_off;

                            $etebar = $check_profile->true_off;



                        } else {

                            //Ø¯Ø± Ø§ÛŒÙ† Ø­Ø§Ù„Øª Ù…Ù‚Ø¯Ø§Ø±ÛŒ Ø§Ø¹ØªØ¨Ø§Ø± Ø¨Ø±Ø§ÛŒ Ø´Ø­Ø¶ Ø¨Ø§Ù‚ÛŒ Ù…ÛŒ Ù…Ø§Ù†Ø¯ Ùˆ Ù…Ù‚Ø¯Ø§Ø±ÛŒ Ø§Ø² Ø§Ø¹ØªØ¨Ø§Ø± Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø´Ø¯Ù‡ Ø§Ø³Øª

                            $newsum = 0;

                            $etebar = $newsum1;

                        }

                    } else {

                        //Ø¯Ø± Ø§ÛŒÙ† Ø­Ø§Ù„Øª Ú©Ø§Ø±Ø¨Ø± Ù‡ÛŒÚ† Ø§Ø¹ØªØ¨Ø§Ø±ÛŒ Ù†Ø¯Ø§Ø±Ø¯

                        $newsum = $newsum1;

                        $etebar = 0;

                    }



//  -4 Ù…Ø­Ø§Ø³Ø¨Ù‡ ÛŒ ØªØ®ÙÛŒÙ Ú©Ø§Ø±Ø¨Ø± Ø¬Ø¯ÛŒØ¯ Ùˆ Ù¾Ø± Ú©Ø±Ø¯Ù† ÙÛŒÙ„Ø¯ code_off Ú©Ù‡ Ù…Ø´Ø®Øµ Ú©Ù†Ù†Ø¯Ù‡ ÛŒ Ø§ÛŒÙ† Ø§Ø³Øª Ú©Ù‡ Ú†Ù‡ ØªØ®ÙÛŒÙÛŒ Ø¨Ù‡ Ø¬Ø² Ø§Ø¹ØªØ¨Ø§Ø± Ø¨Ù‡ Ø´Ø®Øµ ØªØ¹Ù„Ù‚ Ú¯Ø±ÙØªÙ‡ Ø§Ø³Øª

                    //   Ø¨Ø±Ø§ÛŒ Ø§ÛŒÙ†Ú©Ù‡ Ø¨Ø¯ÙˆÙ†ÛŒÙ† Ú©Ø§Ø±Ø¨Ø± Ø¬Ø¯ÛŒØ¯ Ø§Ø³Øª ÛŒØ§ Ù†Ù‡ Ú©Ù‡ Ø§Ú¯Ø± 0 Ø¨Ø§Ø´Ø¯ Ø¬Ø¯ÛŒØ¯ Ø§Ø³Øª Ø¯Ø± ØºÛŒØ± Ø§ÛŒÙ† ØµÙˆØ±Øª Ù†ÛŒØ³Øª

                    $check = \frontend\models\Tblbag::find()->where(['id_user' => Yii::$app->user->getId()])->andWhere(['down_buy' => 1])->count();

                    if ($moaref != 1) {

                        if ($check == 0) {

                            $tblFactor->code_off = 'Ù…Ø¹Ø±Ù Ùˆ Ú©Ø§Ø±Ø¨Ø± Ø¬Ø¯ÛŒØ¯'; // Ø§ÛŒÙ† Ú©Ø§Ø±Ø¨Ø± Ù‡Ù… ØªØ®ÙÛŒÙ Ù…Ø¹Ø±Ù Ùˆ Ù‡Ù… ØªØ®ÙÛŒÙ Ú©Ø§Ø±Ø¨Ø± Ø¬Ø¯ÛŒØ¯ Ø±Ø§ Ø¯Ø§Ø±Ø¯

                            $price_factor = $newsum - ($newsum * 10 / 100);



                        } else {

                            $tblFactor->code_off = 'Ù…Ø¹Ø±Ù'; // Ø§ÛŒÙ† Ú©Ø§Ø±Ø¨Ø± ÙÙ‚Ø· ØªØ®ÙÛŒÙ Ù…Ø¹Ø±Ù Ø±Ø§ Ø¯Ø§Ø±Ø¯

                            $price_factor = $_POST['price-bag'];

                        }

                    } else {

                        if ($check == 0) {

                            $tblFactor->code_off = 'Ú©Ø§Ø±Ø¨Ø± Ø¬Ø¯ÛŒØ¯'; // Ø§ÛŒÙ† Ú©Ø§Ø±Ø¨Ø± ÙÙ‚Ø· ØªØ®ÙÛŒÙ Ú©Ø§Ø±Ø¨Ø± Ø¬Ø¯ÛŒØ¯ Ø±Ø§ Ø¯Ø§Ø±Ø¯

                            $price_factor = $newsum - ($newsum * 10 / 100);

                        } else {

                            $tblFactor->code_off = 'ØªØ®ÙÛŒÙ Ù†Ø¯Ø§Ø±Ø¯'; // Ø§ÛŒÙ† Ú©Ø§Ø±Ø¨Ø± Ù‡ÛŒÚ† ØªØ®ÙÛŒÙÛŒ Ù†Ø¯Ø§Ø±Ø¯

                            $price_factor = $newsum;

                        }

                    }

                    //   Ø¯Ø± Ø§ÛŒÙ† Ù‚Ø³Ù…Øª Ù…Ù‚Ø¯Ø§Ø±ÛŒ Ú©Ù‡ Ù„Ø§Ø²Ù… Ø§Ø³Øª Ø§Ø² Ø§Ø¹ØªØ¨Ø§Ø± Ø´Ø®Øµ Ú©Ù… Ø´ÙˆØ¯ Ù…Ø­Ø§Ø³Ø¨Ù‡ Ù…ÛŒØ´ÙˆØ¯



                    $check_profile->true_off = $profile->true_off - $etebar;

                    $check_profile->save();

                    // Ø¨Ù‡ Ø¯Ùˆ Ø¯Ù„ÛŒÙ„ Ù…Ù‚Ø¯Ø§Ø± Ø§Ø¹ØªØ¨Ø§Ø±ÛŒ Ú©Ù‡ Ù…ØµØ±Ù Ø´Ø¯Ù‡ Ø¯Ø± Ø¬Ø¯ÙˆÙ„ ÙØ§Ú©ØªÙˆØ± Ù†Ú¯Ù‡ Ø¯Ø§Ø±ÛŒ Ù…ÛŒØ´ÙˆØ¯

                    //1- Ù…Ø¯ÛŒØ± Ø¨Ø¯Ø§Ù†Ø¯ Ú©Ù‡ Ù‚ÛŒÙ…Øª Ù†Ù‡Ø§ÛŒÛŒ Ø¨Ø§ Ø§Ø¹Ù…Ø§Ù„ Ø§Ø¹ØªØ¨Ø§Ø±ÛŒ Ú©Ù‡ Ø¨Ù‡ Ø´Ø®Øµ Ø¯Ø§Ø¯Ù‡ Ù…ÛŒ Ø¨Ø§Ø´Ø¯

                    //   2- Ø§Ú¯Ø± Ø¯Ø± Ù‡Ù†Ú¯Ø§Ù… Ù¾Ø±Ø¯Ø§Ø®Øª Ù†Ù‡Ø§ÛŒÛŒ Ù…Ø´Ú©Ù„ÛŒ Ù¾ÛŒØ´ Ø§Ù…Ø¯ Ø§ÛŒÙ† Ù…Ù‚Ø¯Ø§Ø± Ø¨Ù‡ Ù¾Ø±ÙˆÙØ§ÛŒÙ„ Ø´Ø®Øµ Ø¨Ø±Ú¯Ø±Ø¯Ø¯



                    $tblFactor->etebar = $etebar;

                    //  Ú†ÙˆÙ† ÙØ¹Ù„Ø§ ÙÙ‚Ø· Ø§Ø±Ø³Ø§Ù„ ÙÙˆØ±ÛŒ Ù‡Ø³ØªØ´ ÙÙ‚Ø· Ø§ÛŒÙ† Ø­Ø§Ù„Øª Ø±Ø§ Ú†Ú© Ù…ÛŒÚ©Ù†ÛŒÙ…

                    $tblFactor->type_resive = 1;

                    if ($tblFactor->type_resive == 1) {

                        $price_deliver = \frontend\models\PriceDeliver::find()->where(['name' => 'ÙÙˆØ±ÛŒ'])->one();

                        $deliver_price = 0;

                        foreach ($bag2 as $c) {

//Ø¨Ù‡ Ø§Ø²Ø§ÛŒ Ù…Ø­ØµÙˆÙ„Ø§ØªÛŒ Ú©Ù‡ Ø¯Ø± bag  ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ù†Ø¯ Ú†Ú© Ù…ÛŒØ´ÙˆÙ†Ø¯ Ú©Ù‡ Ø§Ø² Ú©Ø¯Ø§Ù… ÙØ±ÙˆØ´Ú¯Ø§Ù‡ Ù‡Ø³ØªÙ† Ø§Ú¯Ø± ÙØ±ÙˆØ´Ú¯Ø§Ù‡ Ù…Ù†Ø·Ù‚Ù‡ Ø§Ø¯Ø±Ø³ Ø®ÙˆØ¯ Ù†Ø¨Ø§Ø´Ù†Ø¯ Ù‡Ø²ÛŒÙ†Ù‡ Ø§Ø±Ø³Ø§Ù„ Ù‡Ù… Ø¨Ù‡ Ù‡Ø²ÛŒÙ†Ù‡ Ù†Ù‡Ø§ÛŒÛŒ Ø§ÙØ²ÙˆØ¯Ù‡ Ù…ÛŒØ´ÙˆØ¯

                            if ($location == 10) {

                                $deliver_price += 0;

                            } else {

                                $deliver_price = 1;

                            }

                        }

                        if ($deliver_price == 1) {

                            $tblFactor->price = $price_factor + $price_deliver->price;

                        } else {

                            $tblFactor->price = $price_factor;

                        }

                    } else {



                        $tblFactor->price = $price_factor;

                    }

                } else {

                    $send['result'] = 0; // Ù…Ø­ØµÙˆÙ„ÛŒ Ø¯Ø± Ø³Ø¨Ø¯ Ø®Ø±ÛŒØ¯ ÙˆØ¬ÙˆØ¯ Ù†Ø¯Ø§Ø±Ø¯

                    $send['msg'] = " Ù…Ø­ØµÙˆÙ„ÛŒ Ø¯Ø± Ø³Ø¨Ø¯ Ø®Ø±ÛŒØ¯ ÙˆØ¬ÙˆØ¯ Ù†Ø¯Ø§Ø±Ø¯";

                    return $send;

                }

            }





            $tblFactor->tel = 333333333;

            $tblFactor->confirm = 0;

            $tblFactor->resive = 0;

            $tblFactor->print = 0;

            $tblFactor->enabel = 1;

            $tblFactor->enabel_view = 1;

            $tblFactor->visibel = 0;

            $tblFactor->addres = $adress;

            $tblFactor->location = $location;

            if ($tblFactor->save(false)) {

                $send['id_fac'] = $tblFactor->id;

                $send['price'] = $tblFactor->price;

                $send['id_user'] = $tblFactor->id_user;

                $send['result'] = 1;

                return $send;



            } else {

                $send['result'] = 0;

                $send['msg'] = "Ø¯Ø± ØµØ¯ÙˆØ± ÙØ§Ú©ØªÙˆØ± Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

                return $send;

            }



        } else {

            print "Ø¯Ø§Ø¯Ù‡ Ù‡Ø§ÛŒ Ø§Ø±Ø³Ø§Ù„ÛŒ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

            exit();

        }





    }



    public function actionListfactor()

    {

        if (Yii::$app->user->isGuest) {

            $send['result'] = 0;

            $send['msg'] = " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

            return $send;

            exit;

        };

        $tblFactor = new Factor();

        $factor = $tblFactor->find()->andWhere(['id_user' => yii::$app->user->getId()])->andWhere(['!=', 'atu', ""])->andWhere('ref != :ref', ['ref' => ""])->orderBy(["id" => SORT_DESC])->all();

        if ($factor == null) {

            $send['result'] = yii::$app->user->getId();

            $send['msg'] = "Ø´Ù…Ø§ Ù‡ÛŒÚ† ÙØ§Ú©ØªÙˆØ± Ù¾Ø±Ø¯Ø§Ø®Øª Ø´Ø¯Ù‡ Ø§ÛŒ Ù†Ø¯Ø§Ø±ÛŒØ¯";

            return $send;

            exit;

        }

        foreach ($factor as $row) {

            $listFactor['idFactor'] = $row->id;

            $listFactor['price'] = $row->price;

            $status = null;

            if ($row->resive == 1 && $row->print == 1 && $row->visibel == 1) {

                $status = "Ø³ÙØ§Ø±Ø´ Ø±Ø§ Ø¯Ø±ÛŒØ§ÙØª Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯ ";

            } else if ($row->print == 1 && $row->visibel == 1) {

                $status = "ØªØ§ Ù„Ø­Ø¸Ø§Øª Ø¯ÛŒÚ¯Ø± Ù¾ÛŒÚ© Ù…ÙˆØªÙˆØ±ÛŒ Ø³ÙØ§Ø±Ø´ Ø´Ù…Ø§ Ø±Ø§ Ù…ÛŒ Ø±Ø³Ø§Ù†Ø¯";

            } else if ($row->visibel == 1) {

                $status = "Ø§Ù¾Ø±Ø§ØªÙˆØ± Ø´Ø±Ú©Øª Ø¯Ø± Ø­Ø§Ù„ Ø¢Ù…Ø§Ø¯Ù‡ Ø³Ø§Ø²ÛŒ Ø³ÙØ§Ø±Ø´ Ø´Ù…Ø§ Ù…ÛŒØ¨Ø§Ø´Ø¯";

            } else if ($row->visibel == 0) {

                $status = "Ø¯Ø± ØµÙ Ø§Ù†ØªØ¸Ø§Ø± Ø¬Ù‡Øª Ø¨Ø±Ø±Ø³ÛŒ";

            }



            $listFactor['status'] = $status;

            $listFactor['date'] = $row->data_ir;

            $list[] = $listFactor;

        }

        $send['result'] = 1;

        $send['factor'] = $list;

        return $send;

    }



    public function actionCheckpayment()

    {

        if (isset($_POST['id']) && $_POST['id'] != null) {

            if (Yii::$app->user->isGuest) {

                print " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

                exit;

            }

            $tblFactor = Factor::find()->where(['id' => $_POST['id']])->one();

            if ($tblFactor == null) {

                $send['result'] = 0;

                $send['msg'] = "Ù…ØªØ§Ø³ÙØ§Ù†Ù‡ Ù¾Ø±Ø¯Ø§Ø®Øª Ø§Ù†Ø¬Ø§Ù… Ù†Ø´Ø¯";

            } elseif ($tblFactor != null) {

                if ($tblFactor->ref != null) {

                    $send['result'] = 1;

                    $send['ref'] = $tblFactor->ref;

                    $send['price'] = $tblFactor->price;

                    $send['atu'] = $tblFactor->atu;

                    $send['msg'] = "Ù¾Ø±Ø¯Ø§Ø®Øª Ø§Ù†Ø¬Ø§Ù… Ø´Ø¯";

                } else {

                    $send['result'] = 0;

                    $send['msg'] = "Ù…ØªØ§Ø³ÙØ§Ù†Ù‡ Ù¾Ø±Ø¯Ø§Ø®Øª Ø§Ù†Ø¬Ø§Ù… Ù†Ø´Ø¯";

                }



            }

        }

        return $send;

    }



    public function actionDetail_product()

    {

        if (isset($_POST["id"]) && $_POST["id"] != null && isset($_POST["catOrPro"]) && $_POST["catOrPro"] != null) {

            $url = yii::$app->urlManager;

            $catOrPro = $_POST["catOrPro"];

            $checFull = 1;

            if ($catOrPro == "d") {

                $tblCat = new Categoryproduct();

                $cat = $tblCat->find()->where(["id_parent" => $_POST["id"]])->andWhere(["enabel" => 1])->andWhere(["enabel_view" => 1])->all();

                $model = new Product();

                $pro = $model->find()->where(["id_category" => $_POST["id"]])->andWhere(["enabel" => 1])->andWhere(["enabel_view" => 1])->all();

                if ($cat != null) {

                    $checFull = 1;

                    foreach ($cat as $catRow) {

                        $sendItemCat["id"] = $catRow->id;

                        $sendItemCat["name"] = $catRow->category;

                        $sendItemCat["description"] = $catRow->alt;

                        $sendCat[] = $sendItemCat;

                    }

                    $send["cat"] = $sendCat;

                } else {

                    $check = 0;

                    $checFull = 0;

                }

                if ($pro != null) {

                    $tblGaleri = new Gallery();

                    $check = 1;

                    foreach ($pro as $proRow) {

                        $img = explode(',', $proRow->id_img);

                        $showImg = $tblGaleri->find()->where(["id" => $img[0]])->one();

                        $sendItemPro["id"] = $proRow->id;

                        ($proRow->id_category != null ? $id_category = $proRow->id_category : $id_category = 0);

                        $sendItemPro["id_cat"] = $id_category;

                        ($showImg->img != null ? $img = $showImg->img : $img = "user.png");

                        $sendItemPro["img"] = $url->hostInfo . "/upload/" . $img;

                        ($proRow->name != null ? $name = $proRow->name : $name = "Ø¨Ø¯ÙˆÙ† Ù†Ø§Ù…");

                        $sendItemPro["name"] = $name;

                        ($proRow->takhfif != null ? $takhfif = $proRow->takhfif : $takhfif = 0);

                        $sendItemPro["price"] = $takhfif;

                        ($proRow->emtiaz != null ? $emtiaz = $proRow->emtiaz : $emtiaz = 0);

                        $sendItemPro["count"] = $emtiaz;

                        $sendPro[] = $sendItemPro;

                    }

                    $send["pro"] = $sendPro;

                } else {

                    $check = 0;

                    if ($checFull == 0) {

                        $checFull = 0;

                    } else if ($checFull == 1) {

                        $checFull = 1;

                    }

                }

                if ($check == 1 && $checFull == 1) {

                    //m ok d ok 2

                    $send["result"] = 2;

                } else if ($check == 1 && $checFull == 0) {

                    //m ok d null

                    $send["result"] = 1;

                } else

                    if ($check == 0 && $checFull == 1) {

                        //D ok m null 3

                        $send["result"] = 3;

                    } else

                        if ($check == 0 && $checFull == 0) {

                            //D null m null

                            $send["result"] = 0;

                        }

                return $send;



            } elseif ($catOrPro == "m") {

                $model = new Product();

                $pro = $model->find()->where(["id" => $_POST["id"]])->one();

                $tblGaleri = new Gallery();

                if ($pro != null) {

                    $img = explode(',', $pro->id_img);

                    $showImg = $tblGaleri->find()->where(["id" => $img[0]])->one();

                    $tblExist = new Exist();

                    $date = new jdf();
                    $time = $date->date('Y/m/d');
                    $time_ir = explode('/', $time);
                    $time_ir[0];
                    $time_ir[1];


                    $exist =   Exist::find()->where(['id_pro' => $_GET['id']])->andWhere(['year' => $time_ir[0]])->andWhere(['month' => $time_ir[1]])
                        ->andWhere('exist_all> :exist_all', ['exist_all' => 0])->all();




                    if ($pro->brand != null) {

                        $txtBrand = $pro->brand;

                    } else {

                        $txtBrand = "Ú©ÛŒÙˆÛŒ";

                    }

                    $shop = "Ø§Ù†ØªØ®Ø§Ø¨ ÙØ±ÙˆØ´Ú¯Ø§Ù‡";

                    if ($exist != null) {

                        foreach ($exist as $rowEx) {

                            $shop .= "," . $rowEx->store . "-" . $rowEx->name_store;

                        }

                    } else {

                        $shop .= "," . "Ù…ÙˆØ¬ÙˆØ¯ Ù†ÛŒØ³Øª";

                    }

                    $sendMainPro["shop"] = $shop;

                    $sendMainPro["result"] = 1;

                    // ($pro->size != null ? $size = $pro->size : $size = 0);

                    // $sendMainPro["size"] = $size;

                    $sendMainPro["id"] = $pro->id;

                    ($pro->id_category != null ? $id_category = $pro->id_category : $id_category = 0);

                    $sendMainPro["id_category"] = $id_category;

                    ($pro->type != null ? $type = $pro->type : $type = 0);

                    $sendMainPro["id_type"] = $type;

                    $sendMainPro["brand"] = $txtBrand;

                    ($showImg->img != null ? $img = $showImg->img : $img = "user.png");

                    $sendMainPro["img"] = $url->hostInfo . "/upload/" . $img;

                    ($pro->description != null ? $description = $pro->description : $description = "ØªÙˆØ¶ÛŒØ­ Ø®Ø§ØµÛŒ Ù†Ø¯Ø§Ø±Ø¯");

                    $sendMainPro["description"] = $description;

                    ($pro->text_meta != null ? $text_meta = $pro->text_meta : $text_meta = "ØªÙˆØ¶ÛŒØ­ Ø®Ø§ØµÛŒ Ù†Ø¯Ø§Ø±Ø¯");

                    $sendMainPro["des"] = $text_meta;

                    $sendMainPro["enabel"] = $pro->enabel;

                    $sendMainPro["enabel_view"] = $pro->enabel_view;

                    ($pro->name != null ? $name = $pro->name : $name = "Ø¨Ø¯ÙˆÙ† Ù†Ø§Ù…");

                    $sendMainPro["name"] = $name;

                    ($pro->price != null ? $price = $pro->price : $price = 0);

                    $sendMainPro["price"] = $price;

                    ($pro->takhfif != null ? $takhfif = $pro->takhfif : $takhfif = 0);

                    $sendMainPro["priceOff"] = $takhfif;

                    ($pro->emtiaz != null ? $emtiaz = $pro->emtiaz : $emtiaz = 0);

                    $sendMainPro["emtiaz"] = $emtiaz;



                    $similar = $model->find()->where(["id_category" => $pro->id_category])->andWhere(["enabel" => 1])->andWhere(["enabel_view" => 1])->all();

                    if ($similar != null) {

                        foreach ($similar as $simRow) {

                            $img = explode(',', $simRow->id_img);

                            $showImg = $tblGaleri->find()->where(["id" => $img[0]])->one();

                            $itmeSimilar["name"] = $simRow->name;

                            $itmeSimilar["des"] = "ØªÙˆØ¶ÛŒØ­Ø§Øª Ú©ÙˆØªØ§Ù‡";

                            $itmeSimilar["id"] = $simRow->id;

                            $itmeSimilar["img"] = $url->hostInfo . "/upload/" . $showImg->img;

                            $sendSimilar[] = $itmeSimilar;

                        }

                    } else {

                        $sendSimilar[] = null;

                    }

                    $send["pro"] = $sendMainPro;

                    $send["similar"] = $sendSimilar;

                    return $send;

                } else {

                    $send["result"] = 0;

                    $send["alert"] = "Ø§ÛŒÙ† Ù…Ø­ØµÙˆÙ„ Ø¯Ø± Ø­Ø§Ù„ Ø­Ø§Ø¶Ø± Ù…ÙˆØ¬ÙˆØ¯ Ù†Ù…ÛŒ Ø¨Ø§Ø´Ø¯";

                    return $send;

                }

            } elseif ($catOrPro == "f") {





                $send["result"] = 0;

                $send["alert"] = "Ø§ÛŒÙ† Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ù†Ø§Ù…ÙÙ‡ÙˆÙ… Ù…ÛŒØ¨Ø§Ø´Ø¯";

                return $send;

            } else {





                $send["result"] = 0;

                $send["alert"] = "Ø§ÛŒÙ† Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ù†Ø§Ù…ÙÙ‡ÙˆÙ… Ù…ÛŒØ¨Ø§Ø´Ø¯";

                return $send;

            }

        } else {

            $send["result"] = 0;

            $send["alert"] = "Ø¯Ø§Ø¯Ù‡ Ù‡Ø§ÛŒ Ø§Ø±Ø³Ø§Ù„ÛŒ Ø¨Ù‡ Ø³Ø§ÛŒØª Ø§Ø´Ø¨Ø§Ù‡ Ø§Ø³Øª";

            return $send;

        }

        $send["result"] = 0;

        $send["alert"] = "Ø§ÛŒÙ† Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ù†Ø§Ù…ÙÙ‡ÙˆÙ… Ù…ÛŒØ¨Ø§Ø´Ø¯";

        return $send;

    }



    /**

     * This is the model class for table "main_app".

     *

     * @property string $

     * @property string $

     * @property string $

     * @property string $

     * @property string $

     * @property string $text3

     */

    // public function actionSignup()

    // {

    //     $p = Yii::$app->getRequest()->getBodyParams();

    //     if (isset($_POST['username']) && $_POST['username'] != null

    //         && isset($_POST['password']) && $_POST['password'] != null

    //         && isset($_POST['tell']) && $_POST['tell'] != null

    //         && isset($_POST['location']) && $_POST['location'] != null

    //         && isset($_POST['moaref']) && $_POST['moaref'] != null

    //         && isset($_POST['adress']) && $_POST['adress'] != null

    //     ) {

    //         $user = User::findByUsername($_POST['username']);

    //         if ($user != null) {

    //             print "Ø§ÛŒÙ† Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ù‚Ø¨Ù„Ø§ Ø«Ø¨Øª Ø´Ø¯Ù‡ Ø§Ø³Øª";

    //             exit;

    //         }

    //         $addres = $_POST['adress'];

    //         $user_moaref = $_POST['moaref'];

    //         $loc = $_POST['location'];

    //         $locat = explode('_', $loc);

    //         $location = $locat[0];



    //         $Profile = new Profile();

    //         if ($user_moaref != "void") {

    //             $user2 = User::find()->where(['username' => $user_moaref])->one();

    //             if ($user2 != null) {

    //                 $Profile->id_user_moaref = $user2->id;

    //             } else {

    //                 $morefEshteb = 1;

    //                 print "Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ù…Ø¹Ø±Ù Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

    //                 exit;

    //             }

    //         }



    //         $user = new User();

    //         $user->username = $p['username'];

    //         $user->setPassword($p['password']);

    //         $user->generateAuthKey();

    //         $auth = Yii::$app->authManager;

    //         $authorRole = $auth->getRole("user");



    //         if (!$user->save()) {

    //             print "Ø¯Ø± Ø°Ø®ÛŒØ±Ù‡ Ú©Ø§Ø±Ø¨Ø± Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

    //             exit;

    //         }

    //         $auth->assign($authorRole, $user->getId());



    //         $Profile->addres = $addres;

    //         $Profile->id_user = $user->getId();

    //         $Profile->role = 'Ú©Ø§Ø±Ø¨Ø±';

    //         $code_find = Profile::find()->all();

    //         $max = 1;

    //         foreach ($code_find as $cf) {

    //             if ($cf->code_off >= $max) {

    //                 $max = $cf->code_off;

    //             }

    //         }

    //         $code = $max + 1;

    //         $Profile->code_off = $code;

    //         $Profile->true_off = 0;

    //         $Profile->true_moaref = 0;

    //         $Profile->location = $location;

    //         if ($Profile->save()) {

    //             if (Yii::$app->getUser()->login($user)) {

    //                 print "1";

    //                 exit;

    //             } else {

    //                 print "Ø¯Ø± ÙˆØ±ÙˆØ¯ Ú©Ø§Ø±Ø¨Ø± Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

    //                 exit;

    //             }

    //         } else {

    //             $user->delete();

    //             print "Ø¯Ø± Ø«Ø¨Øª Ø§Ø·Ø§Ø¹Ø§Øª Ù¾Ø±ÙˆÙØ§ÛŒÙ„ Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

    //             exit;

    //         }

    //     } else {



    //         if (isset($_POST['username']) && $_POST['username'] != null && isset($_POST['password']) && $_POST['password'] != null) {



    //             $username = $p['username'];

    //             $password = $p['password'];

    //             $user = User::findByUsername($username);

    //             if ($user != null) {

    //                 if ($user->validatePassword($password)) {

    //                     Yii::$app->getUser()->login($user);

    //                     print "1";

    //                     exit;

    //                 } else {

    //                     print "Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ùˆ Ù¾Ø³ÙˆØ±Ø¯ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

    //                     exit;

    //                 }

    //             } else {

    //                 print "Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ùˆ Ù¾Ø³ÙˆØ±Ø¯ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

    //                 exit;

    //             }

    //         } else {

    //             print "Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø§Ø±Ø³Ø§Ù„ÛŒ Ø§Ø´Ø¨Ø§Ù‡ Ø§Ø³Øª";

    //         }

    //     }



    // }



    public function actionSignup()

    {



        $p = Yii::$app->getRequest()->getBodyParams();

        if (isset($_POST['username']) && $_POST['username'] != null

            && isset($_POST['password']) && $_POST['password'] != null

            && isset($_POST['tell']) && $_POST['tell'] != null

            && isset($_POST['location']) && $_POST['location'] != null

            && isset($_POST['moaref']) && $_POST['moaref'] != null

            && isset($_POST['adress']) && $_POST['adress'] != null

        ) {



            $user4 = User::findByUsername($_POST['username']);

            if ($user4 != null) {

                print "Ø§ÛŒÙ† Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ù‚Ø¨Ù„Ø§ Ø«Ø¨Øª Ø´Ø¯Ù‡ Ø§Ø³Øª";

                exit;

            }

            $user_moaref = $_POST['moaref'];

            $Profile = new \frontend\models\Profile();

            if ($user_moaref != "void") {

                $user90 = User::find()->where(['username' => $user_moaref])->one();

                if ($user90 != null) {

                    $Profile->id_user_moaref = $user90->id;

                } else {

                    print "Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ù…Ø¹Ø±Ù Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

                    exit;

                }

            }



            $user = new User();

            $user->username = $_POST['username'];

            $user->setPassword($_POST['password']);

            $user->generateAuthKey();

            $auth = Yii::$app->authManager;

            $authorRole = $auth->getRole('user');

            if (!$user->save()) {

                print "Ù…ØªØ§Ø³ÙØ§Ù†Ù‡ Ú©Ø§Ø±Ø¨Ø± Ø°Ø®ÛŒØ±Ù‡ Ù†Ø´Ø¯";

                exit;

            }

            $auth->assign($authorRole, $user->getId());

            $Profile = new \frontend\models\Profile();

            $Profile->addres = $_POST['adress'];

            $Profile->name = $_POST['username'];

            $Profile->lastname = $_POST['username'];

            $Profile->tell = $_POST['tell'];

            $Profile->id_user = $user->getId();

            $Profile->role = 'Ú©Ø§Ø±Ø¨Ø±';

            if ($_POST['moaref'] != "void") {

                $user2 = User::find()->where(['username' => $_POST['moaref']])->one();

                if ($user2 != null) {

                    $Profile->id_user_moaref = $user2->id;

                } else {

                    $Profile->id_user_moaref = 0;

                }

            }



            $code_find = Profile::find()->all();

            $max = 1;

            foreach ($code_find as $cf) {

                if ($cf->code_off >= $max) {

                    $max = $cf->code_off;

                }

            }

            $code = $max + 1;

            $Profile->code_off = $code;

            $Profile->true_off = 0;

            $Profile->true_moaref = 0;

            $loc = $_POST['location'];

            $locat = explode('_', $loc);

            $location =intval($locat[0]) ;

            $Profile->location = $location ;

            if ($Profile->save()) {

                if (Yii::$app->getUser()->login($user)) {

                    print "1";

                    exit;

                } else {

                    print "Ø¯Ø± ÙˆØ±ÙˆØ¯ Ú©Ø§Ø±Ø¨Ø± Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

                    exit;

                }

            } else {



                $user->delete();



                print "Ø¯Ø± Ø«Ø¨Øª Ø§Ø·Ø§Ø¹Ø§Øª Ù¾Ø±ÙˆÙØ§ÛŒÙ„ Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

                exit;

            }

        } else if (isset($_POST['username']) && $_POST['username'] != null && isset($_POST['password']) && $_POST['password'] != null) {



            $username = $p['username'];

            $password = $p['password'];

            $user = User::findByUsername($username);

            if ($user != null) {

                if ($user->validatePassword($password)) {

                    Yii::$app->getUser()->login($user);

                    print "1";

                    exit;

                } else {

                    print "Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ùˆ Ù¾Ø³ÙˆØ±Ø¯ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

                    exit;

                }

            } else {

                print "Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ÛŒ Ùˆ Ù¾Ø³ÙˆØ±Ø¯ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª";

                exit;

            }

        } else {

            print "Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø§Ø±Ø³Ø§Ù„ÛŒ Ø§Ø´Ø¨Ø§Ù‡ Ø§Ø³Øª";

        }

    }



    public function actionLogin()

    {



        $p = Yii::$app->getRequest()->getBodyParams();

        if (isset($_POST['username']) && $_POST['username'] != null && isset($_POST['pass']) && $_POST['pass'] != null) {

            $username = $p['username'];

            $password = $p['pass'];

            $user = User::findByUsername($username);

            if ($user != null) {

                if ($user->validatePassword($password)) {

                    Yii::$app->getUser()->login($user);

                    print "1";

                    exit;

                } else {

                    print "2";

                    exit;

                }

            } else {

                print "2";

                exit;

            }



        } else {

            print "3";

        }

    }



    public function actionCart_update()

    {

        if (isset($_POST['id_bag']) && $_POST['id_bag'] != null && isset($_POST['count']) && $_POST['count'] != null) {

            if (Yii::$app->user->isGuest) {

                print " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

                exit;

            }

            $tblBag = new Tblbag();

            $bag = $tblBag->find()->where(['id' => $_POST['id_bag']])->andWhere(['id_user' => yii::$app->user->getId()])->one();

            if (!filter_var(intval($_POST['count']), FILTER_VALIDATE_INT)) {

                print "ØªØ¹Ø¯Ø§Ø¯ Ø¨Ø§ÛŒØ¯ Ø¹Ø¯Ø¯ Ø¨Ø§Ø´Ø¯";

                exit;

            }

            $bag->count = intval($_POST['count']);

            if ($bag->save()) {

                print "1";

            } else {

                print "Ù„Ø·ÙØ§ Ù…Ø¬Ø¯Ø¯ ØªÙ„Ø§Ø´ Ú©Ù†ÛŒØ¯";

                exit;

            }

        } else if (isset($_POST['id_bag']) && $_POST['id_bag'] != null) {

            if (Yii::$app->user->isGuest) {

                print " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

                exit;

            }

            $tblBag = new Tblbag();

            $bag = $tblBag->find()->where(['id' => $_POST['id_bag']])->andWhere(['id_user' => yii::$app->user->getId()])->one();

            if ($bag->delete()) {

                print "1";

            } else {

                print "Ù„Ø·ÙØ§ Ù…Ø¬Ø¯Ø¯ ØªÙ„Ø§Ø´ Ú©Ù†ÛŒØ¯";

                exit;

            }

        } else {

            print "Ø¯Ø§Ø¯Ù‡ Ù‡Ø§ÛŒÛŒ Ø§Ø±Ø³Ø§Ù„ÛŒ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª ";

            exit();

        }

    }



    public function actionListcart()

    {

        $tblBag = new Tblbag();

        $tblPro = new Product();

        $tblExist = new Exist();

        $tblGaleri = new Gallery();

        $price = 0;

        if (Yii::$app->user->isGuest) {

            $sendAndroid['result'] = 0;

            $sendAndroid['msg'] = " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

            return $sendAndroid;

            exit;

        };

        if (!isset($_POST['idFactor']) && $_POST['idFactor'] == null) {

            $sendAndroid['result'] = 0;

            $sendAndroid['msg'] = "Ø´Ù…Ø§Ø±Ù‡ ÙØ§Ú©ØªÙˆØ± Ø¨Ù‡ Ø³Ø±ÙˆØ± Ø§Ø±Ø³Ø§Ù„ Ù†Ø´Ø¯Ù‡ Ø§Ø³Øª";

            return $sendAndroid;

            exit;

        }

        $Bag = $tblBag->find()->where(['id_user' => yii::$app->user->id])->andWhere(['id_fac' => intval($_POST['idFactor'])])->all();

        if ($Bag == null) {

            $sendAndroid['result'] = 0;

            $sendAndroid['msg'] = "ÙØ§Ú©ØªÙˆØ±ÛŒ Ø¨Ø§ Ø§ÛŒÙ† Ø´Ù…Ø§Ø±Ù‡ Ù…ÙˆØ¬ÙˆØ¯ Ù†Ù…ÛŒ Ø¨Ø§Ø´Ø¯";

            return $sendAndroid;

            exit;

        }

        foreach ($Bag as $rowBag) {

            $pro = $tblPro->find()->where(["id" => $rowBag->id_pro])->one();

            if ($pro == null) {

                $id_pro = $rowBag->id_pro;

                $namePro = "Ø­Ø°Ù Ø´Ø¯Ù‡ Ø§Ø³Øª";

                $priceTakhfif = 1;

            } else {

                $id_pro = $pro->id;

                $namePro = $pro->name;

                $priceTakhfif = $pro->takhfif;

            }

            $img = explode(',', $pro->id_img);

            $showImg = $tblGaleri->find()->where(["id" => $img[0]])->one();

            $createData['count'] = $rowBag->count;

            $createData['id_bag'] = $rowBag->id;

            $createData['idPro'] = $id_pro;

            $createData['name'] = $namePro;

            $createData['price'] = $priceTakhfif;

            $url = yii::$app->urlManager;

            ($showImg->img != null ? $img = $showImg->img : $img = "user.png");

            $createData["img"] = "http://192.168.1.104" . "/upload/" . $img;

            $price = $price + ($rowBag->price * $rowBag->count);

            $arrCraete[] = $createData;



        }

        $sendData['result'] = 1;

        $sendData['msg'] = "Ù…Ø­Ø§Ø³Ø¨Ø§ØªØª ØªÙ…Ø§Ù… Ø´Ø¯";

        $sendData["pro"] = $arrCraete;

        $sendData['price'] = $price;



        return $sendData;



    }





    public function actionCart()

    {



        if (isset($_POST['id']) && $_POST['id'] != null && isset($_POST['shop']) && $_POST['shop'] != null) {

            if (Yii::$app->user->isGuest) {

                print " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

                exit;

            }



            $tblPro = Product::find()->where(["id" => $_POST['id']])->one();

            if ($tblPro == null) {

                print "Ù…ØªØ§Ø³ÙØ§Ù†Ù‡ Ø§ÛŒÙ† Ù…Ø­ØµÙˆÙ„ Ø¨Ù‡ Ø§ØªÙ…Ø§Ù… Ø±Ø³ÛŒØ¯Ù‡ Ø§Ø³Øª";

                exit();

            }

            $tblBag = new Tblbag();

            $tblBag->id_user = yii::$app->user->id;

            $tblBag->id_pro = $tblPro->id;

            $tblBag->count = 1;

//            $tblBag->date = date('Y/m/d');
//
//            $date = new jdf();
//
//            $tblBag->date_ir = $date->date('Y/m/d');

            $tblBag->id_fac = 0;

            $tblBag->enabel = 1;

            $tblBag->down_buy = 0;

            $tblBag->id_size = 0;

            $tblBag->id_color = "o";
//
//            $tblBag->id_all_post = "valid";

            $tblBag->price = $tblPro->takhfif;

            $tblBag->id_discount = 0;

            $stor = explode("-", $_POST['shop']);

            ($stor[0] != null ? $storr = $stor[0] : $storr = 0);

            $tblBag->store = $storr;

            if ($tblBag->save()) {



                print "1";

                exit;

            } else {

                print "Ø¯Ø± Ø°Ø®ÛŒØ±Ù‡ Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ù…Ø´Ú©Ù„ÛŒ ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø±Ø¯";

                exit();

            }

        } else {

            print "Ø¯Ø§Ø¯Ù‡ Ù‡Ø§ÛŒÛŒ Ø§Ø±Ø³Ø§Ù„ÛŒ Ø§Ø´ØªØ¨Ø§Ù‡ Ø§Ø³Øª ";

            exit();

        }

    }



    public function actionDetail_cart()

    {

        $tblBag = new Tblbag();

        $tblPro = new Product();

        $tblExist = new Exist();

        $tblGaleri = new Gallery();

        $price = 0;

        if (Yii::$app->user->isGuest) {

            print " Ø´Ù…Ø§ Ù„Ø§Ú¯ÛŒÙ† Ù†Ú©Ø±Ø¯Ù‡ Ø§ÛŒØ¯";

            exit;

        };

        $Bag = $tblBag->find()->where(['id_user' => yii::$app->user->id])->andWhere(['down_buy' => 0])->all();
        $date = new jdf();
        $time = $date->date('Y/m/d');
        $time_ir = explode('/', $time);
        $time_ir[0];
        $time_ir[1];
        if ($Bag != null) {

            foreach ($Bag as $rowBag) {

                $exist = $tblExist->find()->where(["id_pro" => $rowBag->id_pro])->andWhere(['store' => $rowBag->store])->andWhere(['year' => $time_ir[0]])->andWhere(['month' => $time_ir[1]])->andWhere('exist_all> :exist_all', ['exist_all' => 0])->one();

                $pro = $tblPro->find()->where(["id" => $rowBag->id_pro])->one();

                if ($exist != null) {

                    $img = explode(',', $pro->id_img);

                    $showImg = $tblGaleri->find()->where(["id" => $img[0]])->one();

                    $createData['result'] = 1;

                    $createData['count'] = $rowBag->count;

                    $createData['id_bag'] = $rowBag->id;

                    $createData['id'] = $pro->id;

                    $createData['name'] = $pro->name;

                    $createData['price'] = $pro->takhfif;

                    $createData['msg'] = "Ø§ÛŒÙ† Ù…Ø­ØµÙˆÙ„ Ù…ÙˆØ¬ÙˆØ¯ Ø§Ø³Øª";

                    $url = yii::$app->urlManager;

                    ($showImg->img != null ? $img = $showImg->img : $img = "user.png");

                    $createData["img"] = "http://192.168.1.104" . "/upload/" . $img;

                    $price = $price + ($rowBag->price * $rowBag->count);

                    $arrCraete[] = $createData;

                } else {

                    $createData['name'] = $pro->name;

                    $createData['result'] = 0;

                    $createData['msg'] = "Ø§ÛŒÙ† Ù…Ø­ØµÙˆÙ„ Ø¨Ù‡ Ø§ØªÙ…Ø§Ù… Ø±Ø³ÛŒØ¯Ù‡ Ø§Ø³Øª";

                }

            }

            $sendData['result'] = 1;

            $sendData['msg'] = "Ù…Ø­Ø§Ø³Ø¨Ø§ØªØª ØªÙ…Ø§Ù… Ø´Ø¯";

            $sendData["pro"] = $arrCraete;

            $sendData['price'] = $price;

        } else {

            $sendData['price'] = 0;

            $sendData['result'] = 0;

            $sendData["pro"] = 0;

            $sendData['msg'] = "Ø³Ø¨Ø¯ Ø®Ø±ÛŒØ¯ Ø®Ø§Ù„ÛŒ Ø§Ø³Øª";

        }

        return $sendData;



    }



    public function actionTest2()

    {

//        date_default_timezone_set("Asia/Tehran");

        $p = "d5";

        if (filter_var(intval($p), FILTER_VALIDATE_INT))

            echo "true";

//

//        $parent = date("Y/m/d H:i:sa");

//        echo "<br />".$parent;

//        $p=explode(" ",$parent);

//        $time=$p[1];

//        echo "<br />".$time;

////        $t= strtotime(data("H:i:sa","16:09:09pm"));

////        echo  "<br />";

////        var_dump($t) ;

//        $d1=mktime(2,0,10,10,28,2007);

//        $d2=mktime(4,0,0,10,28,2007);

//        $period=$this->DateDiff($d1,$d2);

//        printf("<br>%s",date("I d.m.Y H:i",$d1));

//        printf("<br>%u hour",$period/3600);

//        printf("<br>%s",date("I d.m.Y H:i",$d2));

//        $year = $time/31556926 % 12;  // to get year

//        $week = $time / 604800 % 52;  // to get weeks

//        $hour = $time / 3600 % 24;    // to get hours

//        $minute = $time / 60 % 60;    // to get minutes

//        $second = $time % 60;

//

//        $p = time("11/25/2017 15:20:26");

//        echo "<br />" . $p = mktime(15, 20, 59, 11, 25, 2017);

//        echo "<br />" . $p1 = mktime(20, 20, 57, 11, 25, 2017);

//        echo "<br />" . $po = $p1 - $p;

//        echo "<br />s" . $s = $po % 60;

//        echo "<br />m=" . $m = $po / 60 % 60;

//        echo "<br />h=" . $h = $po / 3600 % 24;

//

//

//        echo "<br />" . $t = $s + ($m * 60) + ($h * 3600) + (3 * 3600 * 24);

//        $p = $p + $t;

//

//        echo "<br />";

//        var_dump($p);

//        echo "<br />" . date("m/d/Y h:i:s", $p);





    }





}